name: fast_flow
description: "Aplikasi tracking puasa"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  table_calendar: ^3.0.6
  crypto: ^3.0.3
  intl: ^0.19.0
  hijri: ^3.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  http: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  image_picker: ^1.1.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.0
  permission_handler: ^12.0.1
  fl_chart: ^0.65.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.1.10
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  analyzer: ^6.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/